version: '3.5'

services:
# Wordpress
  wordpress:
    image: wordpress:latest
    #好きな名前を入れる
    container_name: wp_cs1
    depends_on:
      - db
    ports:
      - "8000:80"
    restart: always
    environment:
       WORDPRESS_DB_HOST: db:3306
       WORDPRESS_DB_USER: wordpress
       WORDPRESS_DB_PASSWORD: wordpress
       WORDPRESS_DB_NAME: wordpress
    volumes:
       - ./html:/var/www/html
    networks:
      - wpsite

# Database
  db:
    image: mysql:5.7
    #好きな名前を入れる
    container_name: wp_cs1_db
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
       MYSQL_ROOT_PASSWORD: root
       MYSQL_DATABASE: wordpress
       MYSQL_USER: wordpress
       MYSQL_PASSWORD: wordpress
    networks:
      - wpsite
  # phpmyadmin
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    #好きな名前を入れる
    container_name: wp_phpadm1 
    restart: always
    ports:
      - '8080:80'
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root
    networks:
      - wpsite
networks:
  wpsite:
volumes:
  db_data:
